[workspace]
members = ["xtask"]

[package]
name = "autovocoder-nice"
version = "0.1.0"
edition = "2024"

[features]
pretty = ["dep:syn", "dep:prettyplease"] # useful for inspecting generated code

[lib]
crate-type = ["cdylib", "lib"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
codegen-units = 1
lto = "thin"
# (optional) helps reduce binary size
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"

[dependencies]
atomig = { version = "0.4.3", features = ["derive"]}
bitflag-attr = "0.14.0"
nice-plug = "0.2"
nice-plug-egui = "0.3"
autovocoder-dsp = {
    git = "https://github.com/hotspoons/autovocoder",
    rev = "634c6b3eec4a5f81bde5d5885fc88c6ddda2f495"
}
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
egui = "0.35.0"
strum = { version = "0.28.0", features = ["derive"] }

[build-dependencies]
cargo_metadata = "0.23.1"
oxrdf = "0.3.3"
oxttl = "0.2.3"
prettyplease = { version = "0.3.0", optional = true }
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", optional = true }
